name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t acrsqaud6.azurecr.io/patient-service:${{ github.sha }} .

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        subscription-id: "90de0c98-2d25-4094-a834-32b29fdf8003"
        auth-type: 'service-principal'

    - name: Push Docker image
      run: docker push acrsqaud6.azurecr.io/patient-service:${{ github.sha }}

    - name: Logout from Azure Container Registry
      run: docker logout acrsqaud6.azurecr.io
