name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t acrsqaud6.azurecr.io/patient-service:${{ github.sha }} .

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1
      with:
          client-id: "1e96ddac-c32c-4c38-afc7-93417e4674ef"
          client-secret: "jgI8Q~DrGwmUwLtv1vcWhsZ2.zJZaBLuiMdF.aUK"
          tenant-id: "0b889ca3-c111-47fc-b0ed-88a37593b8fa"
          auth-type: 'servicePrincipal'

    - name: Push Docker image
      run: docker push acrsqaud6.azurecr.io/patient-service:${{ github.sha }}

    - name: Logout from Azure Container Registry
      run: docker logout acrsqaud6.azurecr.io
